sudo: required
dist: trusty
language: cpp

python: 2.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
script:
  - cd projects
  - python generate.py linux && pushd linux && make CXX=$COMPILER && pushd divida-tests && ./divida-tests
